FROM txstreet-processor

COPY --chown=root:root --chmod=0555 docker/healthcheck /docker-healthcheck
COPY --chown=root:root --chmod=0555 docker/healthcheck-api /docker-healthcheck-api

HEALTHCHECK \
  --interval=10s \
  --timeout=10s \
  --retries=2 \
  --start-period=20s \
  CMD /docker-healthcheck-api

CMD ["node", "./dist/entry/api"]
