FROM txstreet-processor

COPY --chown=root:root --chmod=0555 docker/healthcheck /docker-healthcheck
COPY --chown=root:root --chmod=0555 docker/healthcheck-websocket /docker-healthcheck-websocket

HEALTHCHECK \
  --interval=10s \
  --timeout=10s \
  --retries=2 \
  --start-period=20s \
  CMD /docker-healthcheck-websocket

CMD ["node", "./dist/entry/websocket-server"]
