FROM txstreet-processor

COPY --chown=root:root --chmod=0555 \
  docker/healthcheck-websocket \
  /docker-healthcheck

HEALTHCHECK \
  --interval=30s \
  --timeout=20s \
  --retries=3 \
  --start-period=40s \
  CMD /docker-healthcheck

CMD ["node", "./dist/entry/websocket-server"]
