#!/bin/sh
set -euo pipefail

port=${1-${HEALTHCHECK_PORT?"HEALTHCHECK_PORT undefined"}}

http_code=`
  curl \
    --silent \
    --show-error \
    -o /dev/stderr \
    -w "%{http_code}" \
    http://localhost:${port}/healthcheck
`

echo '{"http_code": '$http_code'}'

[[ "$http_code" == 200 ]]
